/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropertyTypesRouteImport } from './routes/property-types'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as CatalogSlugIndexRouteImport } from './routes/catalog.$slug.index'
import { Route as CatalogSlugCodeRouteImport } from './routes/catalog.$slug.$code'

const PropertyTypesRoute = PropertyTypesRouteImport.update({
  id: '/property-types',
  path: '/property-types',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSlugIndexRoute = CatalogSlugIndexRouteImport.update({
  id: '/catalog/$slug/',
  path: '/catalog/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSlugCodeRoute = CatalogSlugCodeRouteImport.update({
  id: '/catalog/$slug/$code',
  path: '/catalog/$slug/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/consultation': typeof ConsultationRoute
  '/favorites': typeof FavoritesRoute
  '/gallery': typeof GalleryRoute
  '/property-types': typeof PropertyTypesRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/': typeof PropertiesIndexRoute
  '/catalog/$slug/$code': typeof CatalogSlugCodeRoute
  '/catalog/$slug/': typeof CatalogSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/consultation': typeof ConsultationRoute
  '/favorites': typeof FavoritesRoute
  '/gallery': typeof GalleryRoute
  '/property-types': typeof PropertyTypesRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties': typeof PropertiesIndexRoute
  '/catalog/$slug/$code': typeof CatalogSlugCodeRoute
  '/catalog/$slug': typeof CatalogSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/consultation': typeof ConsultationRoute
  '/favorites': typeof FavoritesRoute
  '/gallery': typeof GalleryRoute
  '/property-types': typeof PropertyTypesRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/': typeof PropertiesIndexRoute
  '/catalog/$slug/$code': typeof CatalogSlugCodeRoute
  '/catalog/$slug/': typeof CatalogSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/consultation'
    | '/favorites'
    | '/gallery'
    | '/property-types'
    | '/properties/$id'
    | '/properties/'
    | '/catalog/$slug/$code'
    | '/catalog/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/consultation'
    | '/favorites'
    | '/gallery'
    | '/property-types'
    | '/properties/$id'
    | '/properties'
    | '/catalog/$slug/$code'
    | '/catalog/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/consultation'
    | '/favorites'
    | '/gallery'
    | '/property-types'
    | '/properties/$id'
    | '/properties/'
    | '/catalog/$slug/$code'
    | '/catalog/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ConsultationRoute: typeof ConsultationRoute
  FavoritesRoute: typeof FavoritesRoute
  GalleryRoute: typeof GalleryRoute
  PropertyTypesRoute: typeof PropertyTypesRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  CatalogSlugCodeRoute: typeof CatalogSlugCodeRoute
  CatalogSlugIndexRoute: typeof CatalogSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/property-types': {
      id: '/property-types'
      path: '/property-types'
      fullPath: '/property-types'
      preLoaderRoute: typeof PropertyTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$slug/': {
      id: '/catalog/$slug/'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug/'
      preLoaderRoute: typeof CatalogSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$slug/$code': {
      id: '/catalog/$slug/$code'
      path: '/catalog/$slug/$code'
      fullPath: '/catalog/$slug/$code'
      preLoaderRoute: typeof CatalogSlugCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ConsultationRoute: ConsultationRoute,
  FavoritesRoute: FavoritesRoute,
  GalleryRoute: GalleryRoute,
  PropertyTypesRoute: PropertyTypesRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  CatalogSlugCodeRoute: CatalogSlugCodeRoute,
  CatalogSlugIndexRoute: CatalogSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
